### ISSUE TITLE
What about $model->log and $model->app?

### ISSUE THREAD

**Issue by akzhan** [jberger/Mojo-TypeModel#1]
$model->log is very often required property.

$model->app is rare one, but app config...

See also https://metacpan.org/pod/Mojolicious::Plugin::Model

**Comment by jberger** [comment]
I think giving a model the app instance is a mistake, indeed that is why I prefer this approach rather than the one that plugin took. That doesn't prevent you from passing in the config on creation and then add it to the copies array, which my example does. The log can be handled in the same way.

I'm happy to talk design discussions, but could we do that on the mojolicious (or better mojolicious-universe) mailing list or else on IRC in the future?
